version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  # Script-api service
  api:
    container_name: script_api_container
    image: script696/script_api:latest
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: script-db
      ADMIN_PANEL: http://script-panel.ru
      TELEGRAM_URL: https://niksemenov.ru
      BOT_TOKEN: 6043745392:AAE_kFGPjvb8d5szU6zaz70QF9gkTuoctSw
      USER_ID: 6401be7c6a607f6f5ad28743
    volumes:
      - static:/app/dist/static
    depends_on:
      - mongo_db
  # Admin panel service
  front:
    container_name: script_admin_panel
    image : script696/script_panel:latest
    depends_on:
      - api
  # Telegram service
  telegram:
    container_name: script_shop
    image : script696/script_shop:latest
    depends_on:
      - api
  # NGINX service
  nginx:
    depends_on:
      - api
      - front
      - mongo_db
    restart: always
    image : script696/script_nginx:latest
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  mongo_db : {}
  static :
    driver: local
