name: Deploy script-panel
on: workflow_dispatch

jobs:
  clone_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: script696/script-panel
        ref: master
        path: app/
